# Generated by Django 4.2 on 2024-05-03 08:32

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=70,
                scale=None,
                size=[300, None],
                upload_to="profiles/",
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="website_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
