# Generated by Django 4.2 on 2024-05-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0007_instructor_bio_instructor_full_name_instructor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
