# Generated by Django 4.2 on 2024-05-02 11:57

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "video",
                    models.ImageField(
                        blank=True,
                        storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                        upload_to="videos/",
                        validators=[
                            cloudinary_storage.validators.validate_video
                        ],
                    ),
                ),
                ("duration", models.IntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                (
                    "course_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
