# Generated by Django 4.2 on 2024-05-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_videocontent_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="posted_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
