# Generated by Django 4.2 on 2024-05-03 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0004_alter_course_posted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="../courses/logo_qn9rcl",
                force_format=None,
                keep_meta=True,
                quality=70,
                scale=None,
                size=[400, None],
                upload_to="courses/",
            ),
        ),
    ]
