# Generated by Django 4.2 on 2024-05-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_instructor_alter_course_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="instructor", new_name="teacher",
        ),
    ]
