# Generated by Django 4.2 on 2024-05-05 18:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_rename_instructor_course_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="courses/logo_qn9rcl",
                force_format=None,
                keep_meta=True,
                quality=70,
                scale=None,
                size=[400, None],
                upload_to="courses/",
            ),
        ),
    ]
