# Generated by Django 4.2 on 2024-05-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("courses", "0007_alter_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
            preserve_default=False,
        ),
    ]
