# Generated by Django 4.2 on 2024-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("courses", "0008_course_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(
                related_name="courses", to="tags.tags"
            ),
        ),
    ]
