# Generated by Django 4.2 on 2024-05-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_course_students_alter_course_teacher"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="is_enrolled",),
    ]
