# Generated by Django 4.2 on 2024-05-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_course_students"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videocontent",
            old_name="course_content",
            new_name="video_contents",
        ),
    ]
