# Generated by Django 4.2 on 2024-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_course_students_alter_course_teacher"),
        ("learner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="enrolled_courses",
            field=models.ManyToManyField(related_name="learners", to="courses.course"),
        ),
    ]
