# Generated by Django 4.2 on 2024-05-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learner", "0002_alter_learner_enrolled_courses"),
    ]

    operations = [
        migrations.RemoveField(model_name="learner", name="enrolled_courses",),
    ]
