# Generated by Django 4.2 on 2024-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learner", "0005_learner_instructor_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="learner", name="instructor_id",),
    ]
