# Generated by Django 4.2 on 2024-05-20 15:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("learner", "0009_alter_learner_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="profiles/default_profile_iryl59",
                force_format=None,
                keep_meta=True,
                null=True,
                quality=70,
                scale=None,
                size=[300, None],
                upload_to="profiles/",
            ),
        ),
    ]
